#!/bin/bash

case "$SNAP_ARCH" in
    *86)
    ARCH="i386-linux-gnu"
    ;;
    *64)
    ARCH="x86_64-linux-gnu"
    ;;
    *)
    ARCH="$SNAP_ARCH-linux-gnu"
    ;;
esac

export LC_ALL="C.UTF-8"
export PERL5LIB="$SNAP/usr/lib/$ARCH/perl-base/:$SNAP/usr/lib/$ARCH/perl5/5.22/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.22.1/:$SNAP/usr/lib/$ARCH/perl/5.22/:$SNAP/usr/lib/$ARCH/perl/5.22.1/"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/pulseaudio/:$LD_LIBRARY_PATH"
export HOME="$SNAP_USER_COMMON"

exec "$@"