#!/bin/bash

case "$SNAP_ARCH" in
    i386) ARCH="i386-linux-gnu" ;;
    amd64) ARCH="x86_64-linux-gnu" ;;
    s390x) ARCH="s390x-linux-gnu" ;;
    ppc64el) ARCH="powerpc64le-linux-gnu" ;;
    armhf) ARCH="arm-linux-gnueabihf" ;;
    arm64) ARCH="aarch64-linux-gnu" ;;
esac

export LC_ALL="C.UTF-8"
export PERL5LIB="$SNAP/usr/lib/$ARCH/perl-base/:$SNAP/usr/lib/$ARCH/perl5/5.26/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.26/:$SNAP/usr/share/perl/5.26.1/:$SNAP/usr/lib/$ARCH/perl/5.26/"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/pulseaudio/:$LD_LIBRARY_PATH"
export HOME="$SNAP_USER_COMMON"

exec "$@"
